### ISSUE TITLE
Version driving packaging

### ISSUE THREAD

**Issue by michaellanguage** [pdm-project/pdm#1195]
Imaging adding web3 to your project which require "eth-utils>=2.0.0,<3.0.0", and tronapi which require "eth-utils>=1.3.0,<2.0.0",

https://github.com/ethereum/web3.py/blob/master/setup.py
https://github.com/iexbase/tron-api-python/blob/master/setup.py

if you can package each module in a folder in version driving fashion using concept derived from   https://skippd.medium.com/handling-multiple-versions-of-a-package-in-python-73055998ce73

where in the root of the package when ever a reference is made to the required package by a module the module is pointed to the path of the version in the  `__init__.py` injected . ie
```python
import os
import sys
sys.path.insert(1,os.path.abspath('tronapipath/eth-utils/3.0.0'))
```

before this statement
https://github.com/iexbase/tron-api-python/blob/master/tronapi/trx.py
```python
from trx_utils import is_integer, is_hex
```
```python
import os
import sys
sys.path.insert(1,os.path.abspath('tronapipath/eth-utils/3.0.0'))
from trx_utils import is_integer, is_hex
```
with this i think you guys have solved  dependency hell hunting every python programmer out there finding way to plug all your requirements into a single usable package without breaking one for other..

**Comment by frostming** [comment]
This won't work, at least in your proposed way. The problem is Python's import system caches the module on the first import can won't do anything on subsequent imports. So no matter how you change the `sys.path`. There will be only one `trx_utils`, either `3.0.0` or `1.0.0`.

In fact, the idea of multiversion was [explored several years ago](https://github.com/mitsuhiko/multiversion), but it was proved not useful since it will change how pip install packages.

**Comment by michaellanguage** [comment]
Thank you for the info, i hope there will be solution or another approach towards this problem.

**Comment by frostming** [comment]
> Thank you for the info, i hope there will be solution or another approach towards this problem.

It is difficult, if not impossible, with the current Python import system.

Say you have package A depending on `foo>=2`, and B depending on `foo<2`, and you managed to install `foo 1.0` and `foo 2.0` somehow, in different paths.

What happens when `import B; B.get_foo_object()` inside A? A thinks it returns an object from `foo`, but it isn't, it is in fact from a totally different `foo`, but how does A know that?

**Comment by michaellanguage** [comment]
Thank you, i learnt the hard way had to try this out, today learnt about Python's import system cache, which wouldn't let this design to work, am glad i did not waste my time trying to pursue this goal.

https://github.com/michaellanguage/versionmultipython
