### ISSUE TITLE
Feature Request: Make CA bundle configurable

### ISSUE THREAD

**Issue by sleiner** [pdm-project/pdm#1240]
## Problem description

- Some users (e.g. me) are using package repositories other than pypi.org.
- These are (of course) accessed over an encrypted HTTPS connection.
- The repository server's certificate might be signed by a private CA.
- In this case, PDM will fail to access the repository via HTTPS.

## There is a known workaround

As the requests are being made using the [requests](https://pypi.org/project/requests/) library, I can [override the cert store using `REQUESTS_CA_BUNDLE`](https://requests.readthedocs.io/en/latest/user/advanced/#ssl-cert-verification) so that my system's CA store is used instead of [certifi](https://pypi.org/project/certifi/). E.g. for Debian:

```bash
export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
```

## The solution I would prefer

I'm seeing some problems with the workaround above:

 - As a user, I might not want to have `REQUESTS_CA_BUNDLE` set for every terminal session. In that case, I have to remember to set it manually when using PDM.
 - *If I would want to set the env variable globally*, I still have to know how to do that properly.

So, I would prefer to be able to set the CA bundle in PDM's configuration, similar to `pip`'s `global.cert` option, e.g. `pypi.cert` or `pypi.ca`. This could be set to a file path (e.g. `/etc/ssl/certs/ca-certificates.crt` for Debian).

**Comment by frostming** [comment]
SGTM, would you like to contribute?

**Comment by GooseYArd** [comment]
piggybacking onto this issue- my employer uses a private pypi repo having a server cert issued by a non-public CA, but also requiring a client cert issued by that CA. Prior to pdm 2.0.x, the pip config "client-cert" and "cert" settings appeared to be used by pdm, but I just noticed that has stopped working with 2.0.x.

Since the user's client cert will obviously vary from user to user, I think a global pdm setting would probably be ideal for this. A few packages, like requests, will accept either a boolean for "verify", or a path to some CA bundle as its value- I've always felt that was a slightly weird interface, but does avoid the need for an additional parameter for the CA cert.

For the client cert/key, pip is also weird and requires a single argument, "client_cert" which is treated as a path to a file containing but the client cert and key in pem format. Since pip users would necessarily have their cert and key in such a file anyway, if pdm were use the same scheme it'd be convenient.

If someone in the thread creates a branch which implements the CA bundle configuration option, I'd be happy to use that as an example on which to base a branch which supports client cert options as well.

**Comment by sleiner** [comment]
> SGTM, would you like to contribute?

Sure! :-) It might take a few days though 😅
