### ISSUE TITLE
Inconsistent dependency resolution when subdependencies are specified

### ISSUE THREAD

**Issue by lyz-code** [pdm-project/pdm#1355]
- [x] I have searched the issue tracker and believe that this is not a duplicate.
`pdm` doesn't return the same result when adding a new dependency if one of their sub dependencies is already pinned.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

From a clean environment with `pdm init` run:

```bash
pdm add flakeheaven 'flake8>=3.9.2'
```

## Actual behavior

`flakeheaven` installed version is `0.11.0` while latest is 3.0.0.

```
  ✔ Install entrypoints 0.4 successful
  ✔ Install mccabe 0.7.0 successful
  ✔ Install colorama 0.4.5 successful
  ✔ Install pycodestyle 2.9.1 successful
  ✔ Install toml 0.10.2 successful
  ✔ Install pyflakes 2.5.0 successful
  ✔ Install flake8 5.0.4 successful
  ✔ Install flakeheaven 0.11.0 successful
  ✔ Install urllib3 1.26.12 successful
  ✔ Install pygments 2.13.0 successful
```

## Expected behavior

However if from the clean environment you only run `pdm add flakeheaven` without specifying the `flake8` dependency you get the `3.0.0` version. That installs a version of `flake8 == 4.0.1` that matches the constrain `flake8>=3.9.2`. So the command `pdm add 'flake8>=3.9.2' flakeheaven` should at least install `flake8 == 4.0.1` and `flakehell == 3.0.0`

```

  ✔ Install entrypoints 0.4 successful
  ✔ Install mccabe 0.6.1 successful
  ✔ Install colorama 0.4.5 successful
  ✔ Install pycodestyle 2.8.0 successful
  ✔ Install toml 0.10.2 successful
  ✔ Install flake8 4.0.1 successful
  ✔ Install pyflakes 2.4.0 successful
  ✔ Install flakeheaven 3.0.0 successful
  ✔ Install urllib3 1.26.12 successful
  ✔ Install pygments 2.13.0 successful
```

However if you run on a clean environment `pdm add 'flakeheaven>=1.0.0' 'flake8>=3.9.2'` you get the same result as with `pdm add flakeheaven`

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.1.3
Python Interpreter:
  /tmp/tmp.ANJTs8czk0/env/bin/python (3.9)
Project Root:
  /tmp/tmp.ANJTs8czk0
Project Packages:
  None
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.10",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "4.19.0-5-amd64",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Debian 4.19.37-5+deb10u1 (2019-07-19)",
  "python_full_version": "3.9.10",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}

```

**Comment by frostming** [comment]
It is due to the priority picker of pdm's resolver.

In your first attempt: `pdm add flakeheaven 'flake8>=3.9.2'`, `flake8` will be first picked to pin, since it has more *concrete* specifiers, and `flake8==5` will be pinned, then PDM will try to find a candidate of `flakeheaven` that doesn't limit `flake8` to `<4`.

1. Resolve `flake8` -> `flake8==5`
2. Resolve `flakeheaven` given `flake8==5` -> `flakeheaven==0.11.0`

The second time, you install `flakeheaven` first, this is a *free* constraint, and the latest version will be pinned, following resolution will just try to reuse the pinned version of `flake8`.

1. Resolve `flakeheaven` -> `flakeheaven==3.0.0`
2. Resolve `flake8` given `flakeheaven==3.0.0` -> `flake8==4`

The third time, `pdm add 'flakeheaven>=1.0.0' 'flake8>=3.9.2'`, this time `flakeheaven` wins after comparing the priority. So it works the same as the second time.

The PDM's resolver is designed so that the earlier pinned packages will strongly affect the following resolution, and bad decisions in an early stage often come with a huge price tag.

So the suggestion is if you know such constraints between packages, in your case, `flakeheaven` doesn't work with `flake8>=5`, manually specify `flake8<5` to reduce the number of trials and errors for the resolver.

**Comment by frostming** [comment]
I think #1354 has a similar cause to this one, you can solve it by fine-tuning the dependencies, especially `flake8` and `flakeheaven`.

**Comment by lyz-code** [comment]
Thank you for the clear explanation, I'll update you on my progress on the other issue
