### ISSUE TITLE
Allows Specifying the Insertion Position of Extra Arguments Supplied to `pdm run`

### ISSUE THREAD

**Issue by Xdynix** [pdm-project/pdm#1507]
## Is your feature request related to a problem? Please describe.

I'm using PDM scripts to both run commands in PDM environment, and also as a shorthand for providing common parameters.

For example, in a Django project, it's common to run commands with `manage.py`. I will use script like

```toml
manage = { cmd = [
    'python', 'manage.py',
] }
```

So that I can use command `pdm manage migrate`, instead of `pdm run python manage.py migrate`. Where the common prefix `python manage.py ...` can be reused.

However, I found that one of my tools (specifically, [`pre-commit`](https://pre-commit.com/)) has commands and arguments in this format:

```shell
pre-commit install --config somewhere/config.yml
pre-commit autoupdate --config somewhere/config.yml
pre-commit run --config somewhere/config.yml
```

The parameters like `--config` must come after commands like `install`. If I create script

```toml
pre-commit = { cmd = [
    'pre-commit', '--config', 'somewhere/config.yml',
] }
```

and execute `pdm run pre-commit install`, the additional argument `install` will always be appeneded to the `cmd` and resulting

```
pre-commit --config somewhere/config.yml install
```

which is invalid for `pre-commit`.

Since the common parts (`pre-commit` and `--config somewhere/config.yml`) of the commands are not a prefix, there is no way for me to create shorthand PDM scripts for them.

**It would be greate if we can specify the insertion position of extra arguments supplied to `pdm run`.**

## Describe the solution you'd like

We can provide an optional placeholder to the `cmd`. e.g.:

```toml
pre-commit = { cmd = [
    'pre-commit', '$args', '--config', 'somewhere/config.yml',
] }
```

**Comment by noirbizarre** [comment]
I am interested into this because I might have the same issue with composite commands.

After a lots of thinking, I came to the conclusion that the best approach is the same as `tox`: https://tox.wiki/en/latest/example/general.html#interactively-passing-positional-arguments

Remains one issue: until now all args are given to the tail of the command by default and while the `posargs` is helpful, I think we should keep the default behavior if the posargs is not detected in the command (same for composite, if no posarg is given, keep the current pattern apply the posargs to the tail of every command).

Does it seems an acceptable solution/compromise ?

**Comment by frostming** [comment]
SGTM, while I prefer the name `args` @noirbizarre

**Comment by noirbizarre** [comment]
There it is #1533 🚀
