### ISSUE TITLE
Recursive installation of editable dependencies

### ISSUE THREAD

**Issue by bland328** [pdm-project/pdm#1771]
## Is your feature request related to a problem? Please describe.

When editable dependency A depends on editable dependency B, dependency B fails because its dependencies are not installed.

## Describe the solution you'd like

I'm using `pdm` within a monorepo focused on local development, so editable dependency chains are common for me, and any workflow requiring generation of wheels or eggs won't likely be the right solution for me.

I'd like for `pdm` to (at least optionally) recursively install editable dependencies.

`poetry` does handle this case as I desire, but I otherwise prefer `pdm` for a variety of reasons, so I'm hoping this feature might be forthcoming.

**Comment by frostming** [comment]
> I'm using `pdm` within a monorepo focused on local development, so editable dependency chains are common for me, and any workflow requiring generation of wheels or eggs won't likely be the right solution for me.

I understand, but PDM is backend-agnostic and therefore relies on the `project.dependencies` and `project.optional-dependencies` lists defined in the PEP 621 standard for its dependencies. It won't look at the *tool-specific` `tool.pdm.dev-dependencies` at all.

But as a workaround, since you are working on a monorepo, every editable dependency should be one cared by your development, so it should be listed in the top-most package's `dev-dependencies`, and only write normal dependencies in children's `project.dependencies`. PDM knows how to install them correctly.
