### ISSUE TITLE
Publish method supports working with any package

### ISSUE THREAD

**Issue by shvilime** [pdm-project/pdm#2073]
I distribute my application like rpm file and publish it in custom yum repository.
I tried to use publish command like
`pdm publish --no-build --repository https://myrepo/yum/ --username user --password pass`
but received error message
`[PdmUsageError]: Unknown distribution file type: dist/client-2.1.0-1.rpm`
Is it possible to add in command publish working with distribution file in other formats with function just to upload the artifact to repo?
Of course, I can write pdm script and use command with `curl` to upload the dist file, but it would be cool to use standard functionality.

**Comment by pawamoy** [comment]
I don't think that's in the scope of PDM, but let see what @frostming thinks.

**Comment by shvilime** [comment]
> I don't think that's in the scope of PDM, but let see what @frostming thinks. Could maybe be done with a plugin 🙂

IMHO the plugin more suitable for task to create rpm package, than to publish it.

**Comment by pawamoy** [comment]
If a plugin can enhance the functionality of `pdm publish`, then it makes much more sense to me to do that with a plugin rather than integrate the feature natively. There are many different file formats for packages, and many different kinds of repository for all the different operating systems that exist. Surely we don't want to maintain everything in PDM directly.

**Comment by frostming** [comment]
`pdm publish` talks to Python simple repository. Other repository types are out of the scope of PDM and the upload logic is totally different, you can write your own tool or script to do that.

Closing it now.
