### ISSUE TITLE
Shared cache cannot support overlapping directory structures

### ISSUE THREAD

**Issue by blakewatters** [pdm-project/pdm#2105]
The issue here is that related packages distributed independently with an overlapping module path with clobber one another when the shared cache is enabled. The example, `gcloud-aio-storage` and `gcloud-aio-auth` install to a common path of `gcloud.aio` and nest their subdirectories under the shared root. When the shared cache is enabled, we get last-writer-wins semantics where only the last package installed has its sources stored in the cache.

- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

1. Enable the shared cache: 
2. Install `gcloud-aio-storage`: `pdm add gcloud-aio-storage`
3. Install `gcloud-aio-taskqueue`: `pdm add gcloud-aio-taskqueue`
4. Write a script attempting to import `from gcloud.aio.storage import Storage`

## Actual behavior

The import fails because of a shared dependency on `gcloud.aio.auth` which is not available in the cache.

## Expected behavior

Each component library should be able to add its own sources into `gcloud/aio/<whatever>` namespace and become available for import in the cache.

This works when the shared cache is disabled.

## Environment Information

```console
pdm info && pdm info --env
PDM version:
  2.7.4
Python Interpreter:
  /Users/blakewatters/.pyenv/versions/3.11.4/bin/python3 (3.11)
Project Root:
  /Users/blakewatters/Projects/osiris-worktrees/test-submissions-api
Local Packages:
  /Users/blakewatters/Projects/osiris-worktrees/test-submissions-api/__pypackages__/3.11
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.4",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "22.5.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:23 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6020",
  "python_full_version": "3.11.4",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
The strategy we are currently using is to create symbolic links for folders as much as possible, in order to minimize the number of links. Namespace package must follow the common convention so that we can predict it will contain sub packages and won't create symlink for the top package.

But apparently google doesn't follow rules well.

The only way to solve this is to be stupid and create symlink for each file in the package. What do you think?

**Comment by pawamoy** [comment]
If I understand the fix correctly, the issue was actually that these packages were not detected as namespace packages, and not because of the cache. Because looking at my local cache, namespace packages seem perfectly supported: my mkdocstrings-python package uses the top-level `mkdocstrings_handlers` namespace, and it is cached in `~/.cache/pdm/packages/mkdocstrings_python-1.1.2.1.1.1-py3-none-any` (then `lib/mkdocstrings_handlers`), so each package is properly isolated, and namespaces are merged together when installing from the cache.

**Comment by frostming** [comment]
> If I understand the fix correctly, the issue was actually that these packages were not detected as namespace packages

Yes, At first, I planned to explain and refuse this, but finally it turned out a low-hanging fruit I was not aware of. Now it should support all legacy namespace mechanisms.
