### ISSUE TITLE
docs "pytest fixtures" typo

### ISSUE THREAD

**Issue by themattmorris** [pdm-project/pdm#2152]
From [this page]:

![image](https://github.com/pdm-project/pdm/assets/16111337/8e68d13c-dc0b-4d0e-8d54-3bb264b4cde0)

I was going to open a PR to simply remove the trailing `#`, but I cannot figure out why that is even there.  [This page](https://[raw.githubusercontent.com/pdm-project/pdm/bdcfd49686dbebd9004be5438d4d4ff8cdbefa09/docs/docs/dev/fixtures.md) has not been updated in awhile, and it has not trailing `#`.

I know this is really minor, but wanted to report it as it was something I noticed when browsing the docs.  Thanks for this awesome project!

**Comment by frostming** [comment]
That's weird, it also shows in the "Reference -> API Reference".

ping @pawamoy if you have any clue.

**Comment by pawamoy** [comment]
Possibly due to the new MkDocs version, 1.5, which removed the upper bound on Python-Markdown. I'll check in one of my projects.

**Comment by pawamoy** [comment]
Seems to come from the `_ExtractTitleTreeprocessor` Markdown extension added by MkDocs. Continuing investigation :slightly_smiling_face:

**Comment by pawamoy** [comment]
@oprypin, in `_ExtractTitleTreeprocessor`, at this line

```python
if len(el) > 0 and el[-1].tag == 'a' and not (el.tail or '').strip():
```

...there's a HTML stash item in the element tail (like `'\n\x02wzxhzdk:0\x03'`), so the last condition is false and the anchorlink does not get removed, so the title picks up the character of the permalink (`#`).

I'm not sure to understand why this happens now. Is this a matter of priority in the registered extensions (pre/block/tree/post-processors)? I guess previously the HTML stash item containing the rendered mkdocstrings HTML would get unstashed before this extension would extract the title? Note that this only happens when there's a mkdocstrings-injected object after the Markdown heading.

**Comment by pawamoy** [comment]
It seems `_ExtractTitleTreeprocessor` is new in MkDocs 1.5, so the logic was probably different before. Is it possible that this issue comes from how we handle the Markdown blocks in our mkdocstrings extension? Would an additional newline in front of the stashed HTML fix this? `'\n\n\x02wzxhzdk:0\x03'`

**Comment by oprypin** [comment]
Oh hm wow, it seems like `_ExtractTitleTreeprocessor` indeed can't deal with the logic of having a `tail`. I wonder why there's the check for it at all.

**Comment by oprypin** [comment]
I'm pretty sure it was supposed to be this.

```diff
diff --git a/mkdocs/structure/pages.py b/mkdocs/structure/pages.py
index 34c0bc764..e42faffcd 100644
--- a/mkdocs/structure/pages.py
+++ b/mkdocs/structure/pages.py
@@ -437,7 +437,7 @@ class _ExtractTitleTreeprocessor(markdown.treeprocessors.Treeprocessor):
         for el in root:
             if el.tag == 'h1':
                 # Drop anchorlink from the element, if present.
-                if len(el) > 0 and el[-1].tag == 'a' and not (el.tail or '').strip():
+                if len(el) > 0 and el[-1].tag == 'a' and not (el[-1].tail or '').strip():
                     el = copy.copy(el)
                     del el[-1]
                 # Extract the text only, recursively.
```

I'll look into releasing this fix very soon

**Comment by pawamoy** [comment]
The fix was merged, we just have to wait for a release, we can close :slightly_smiling_face: 
Thanks again @oprypin
