### ISSUE TITLE
resolution infinite loop with skypilot[aws] and dvc[s3]

### ISSUE THREAD

**Issue by deronnax** [pdm-project/pdm#2545]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

```
➜ pdm add -v  "skypilot[aws]" "dvc[s3]"
```

Output is too big to paste it here because PDM goes into a somewhat resolution infinite loop, see the attached output: [pdm-infinite.txt](https://github.com/pdm-project/pdm/files/13876408/pdm-infinite.txt)

## Actual behavior

PDM loses itself in a endless resolution. It takes too long (more than 3 minutes on a recent macbook on a good connection) to wait for it to end, but from what I can see from the logs, it would probably end in resolution failure.

## Expected behavior

Resolution success.

## Environment Information

```bash
➜  pdmtut pdm info && pdm info --env
PDM version:
  2.11.2
Python Interpreter:
  /Users/mathieu/Library/Application Support/pdm/venvs/pdmtut-jVb07vzb-3.10/bin/python (3.10)
Project Root:
  /private/tmp/pdmtut
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.10.13",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "23.2.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 23.2.0: Wed Nov 15 21:59:33 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T8112",
  "python_full_version": "3.10.13",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
It is not an infinite loop, just too slow to reach to the solution. You can search for `new pin boto3` and find the version is actually decreasing. Just these dependency versions are mutually constrained(it's mainly because [aioboto3 uses rather strict version ranges](https://pypi-browser.fming.dev/package/aiobotocore)), and there are quite a few package versions of boto3, making it hard for the resolver to get the right one.

I would suggest manually give `boto3 <1.33.14, >=1.33.2` to speed up the resolver.

**Comment by v3ss0n** [comment]
I think it should be highlighted in PDM manual. I am facing a lot of that kind of issue , making me remove some depedencies because of that.

Now i am facing it again due to s3fs + boto3
