### ISSUE TITLE
Document call scripts when using the "src layout"

### ISSUE THREAD

**Issue by billylanchantin** [pdm-project/pdm#3106]
## Is your feature/enhancement proposal related to a problem? Please describe.

I'm unclear on how to run call scripts under the "src layout" structure. I apologize in advance if the documentation is present but I missed it.

My project structure looks like this:

```
my_app/
    │
    ├── pyproject.toml
    │
    ╞══ src/
    │   │
    │   ╘══ my_app/
    │       │
    │       ├── __init__.py
    │       ├── my_module_1.py
    │       └── my_module_2.py
    │
    ╘══ tests/
        │
        └── my_test.py
```

When I add the following to my `pyproject.toml`:

```toml
[tool.pdm.scripts]
my_module_1 = "my_app.my_module_1:main"
```

Then run the following from the project root:

```
pdm run my_module_1
```

I get:

```
[PdmUsageError]: Command 'my_app.my_module_1:main' is not found in your PATH.
```

## Describe the solution you'd like

I'd like clear documentation on how to run a call script when using the src layout structure. I've tried many variations on the above but I've not been able to get it to work.

Either that, or a note if call scripts aren't supported when using the src layout.

## Additional info

* If possible, I'd like to keep the style of `import my_app.my_module_2` from within `my_module_1.py` rather than prefixing all imports with `src.`
* I'm not planning on distributing this package and so have `distribution = false` in my `pyproject.toml`. I'm not sure it that's relevant.

**Comment by frostming** [comment]
You are probably confusing `tool.pdm.scripts` with `project.scripts`, but the latter is a distribution-only field so just ignore it now.

For `tool.pdm.scripts` the way to define a call script is different: https://pdm-project.org/en/latest/usage/scripts/#call
but because you are not installing the project itself, `my_app` never has a chance to be exposed in import paths(This process is done by installing the project). So `src` is just a regular python package, you need to prefix the import path with `src.`

To conclude, the correct config is:

```toml
[tool.pdm.scripts]
my_module_1.call = "my_app.my_module_1:main"
```

**Comment by frostming** [comment]
A bit more explanation on why I closed this. I am a bit burnt out by continuous misunderstandings on so many concepts in Python packaging that I couldn't cover in the docs. I can't anticipate what can stuck people, I just don't know.

So instead of requesting a doc improvement, just send a PR please.

**Comment by pawamoy** [comment]
Sorry to hear you're burnt out @frostming. I'm less active in the issues and discussions because I have lots to do in my own projects and I have to prioritize, but I still watch from afar, and PDM is indeed getting an endless stream of questions 😕 I suppose that's the price of successful and popular software.

It's OK to take a break from community support, or from GitHub entirely!

**Comment by frostming** [comment]
@pawamoy Thank you for your kind words, It's okay, I can adjust myself. I just need to vent.

Keep up with the great work with all your open source projects, there's a lot of them.

**Comment by pawamoy** [comment]
Alright :smile: 

You might prefer I delete this toot then: https://fosstodon.org/@pawamoy/112965186602361387! Let me know.

**Comment by billylanchantin** [comment]
Hi @frostming,

Thank you for your response. I've gotten my project in working order and things are running smoothly.

I'm very sorry you've been feeling burnt out on this project and that I contributed to it. That was not my intent. Given what's been said here, I would like to be part of the solution and not part of the problem.

> A bit more explanation on why I closed this.

You were right to close it. Don't worry about that. I was not offended nor should I have been.

> Instead of requesting a doc improvement, just send a PR please.

I'm also an open source contributor/maintainer. I'm very willing to contribute where I can. And I know it's frustrating when someone's question/issue reveals by its nature that they are a beginner. It means you may not even be able to point them to the part of the documentation they need because they wouldn't understand it.

That said, I freely admit I that in this case I _am_ that beginner. I couldn't send a PR because I didn't know what the solution to my issue was.

> PDM is indeed getting an endless stream of questions 😕 I suppose that's the price of successful and popular software.

This part is particularly tragic. I saw many other issues like mine quickly addressed, so I raised one. It honestly felt like the vibe around here. I'm sorry I piled on! That was my bad.

That said, there may be an opportunity to improve things here. Maybe a note in the README about which issues are appropriate? Maybe links to external docs?

> I am a bit burnt out by continuous misunderstandings on so many concepts in Python packaging that I couldn't cover in the docs. I can't anticipate what can stuck people, I just don't know.

That seems quite frustrating and again I'm sorry about that. I'll try to shed light on my particular misunderstanding if it helps.

What I think tripped me up was that it seems like "distribution" is a bit of a misnomer. I assumed that stuff didn't apply to my use case because I didn't plan on publishing my code. I didn't realize that it meant something else too.

If you would like, I can try to contribute some examples of fully working toy projects. It may go a long way to helping newcomers navigate the interactions of the different configuration options.

**Comment by pawamoy** [comment]
Thanks for your thoughtful answer @billylanchantin. There's nothing to blame you for, don't worry ^^ It's just how it is in projects used by large demographics, you get a lot of confused users asking questions, and when you're (almost) the only one answering, it's tiring :/ Anyway, you're a maintainer, you know these things, no need to elaborate :)
