### ISSUE TITLE
Git repo dependency and alternative dev-dependency resolution error

### ISSUE THREAD

**Issue by marcel-goldschen-ohm** [pdm-project/pdm#3147]
I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

in pyproject.toml:
```
[project]
dependencies = [
    "some_pypi_package",
    "some_repo @ git+https://github.com/user/some_repo"
]

[tool.pdm.dev-dependencies]
dev = [
    "-e some_pypi_package @ file:///${PROJECT_ROOT}/../some_pypi_package",
    "-e some_repo @ file:///${PROJECT_ROOT}/../some_repo"
]
```
where local installs of some_pypi_package and some_repo for development are in the same folder as the project directory. Run `pdm lock --dev` or `pdm lock --prod`.

## Actual behavior

Running `pdm lock --dev` or `pdm lock --prod` results in a Lock failed error: ResolutionImpossible due to conflict between some_repo in dependencies and some_repo in dev-dependencies. First, if some_repo is only listed in either dependencies or dev-dependencies everything works fine, so it's not the dependency itself that is broken. The confusing thing is that there is no such conflict for some_pypi_package, and if some_repo is removed everything work fine. By that I mean `pdm lock --dev` uses some_pypi_package from dev-dependencies and  `pdm lock --prod` uses some_pypi_package from dependencies. Why doesn't this also work in that manner for some_repo?

## Expected behavior

I would expect `pdm lock --dev` to use some_repo from dev-dependencies and  `pdm lock --prod` uses some_repo from dependencies just like how it behaves for some_pypi_package.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
INFO: Inside an active virtualenv /opt/miniconda3/envs/test, reusing it.
Set env var PDM_IGNORE_ACTIVE_VENV to ignore it.
PDM version:
  2.18.1
Python Interpreter:
  /opt/miniconda3/envs/test/bin/python (3.12)
Project Root:
Local Packages:
  
INFO: Inside an active virtualenv /opt/miniconda3/envs/test, reusing it.
Set env var PDM_IGNORE_ACTIVE_VENV to ignore it.
{
  "implementation_name": "cpython",
  "implementation_version": "3.12.1",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "23.6.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; 
root:xnu-10063.141.2~1/RELEASE_ARM64_T6000",
  "python_full_version": "3.12.5",
  "platform_python_implementation": "CPython",
  "python_version": "3.12",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
That's because both requirements are considered in resolution when running `pdm lock --dev`, but PDM has to pick only one candidate to match both. So:

`file:///${PROJECT_ROOT}/../some_pypi_package`(candidate) works for both `some_pypi_package` and `file:///${PROJECT_ROOT}/../some_pypi_package` because of a [special handling](https://github.com/pdm-project/pdm/blob/fbaa7c140e1f4aa421e681bc72bdbfcd754b7a0b/src/pdm/resolver/providers.py#L250-L270) for this case to check version matching only

But for `some_repo`, there are two different requirements `some_repo @ git+https://github.com/user/some_repo` and `some_repo @ file:///${PROJECT_ROOT}/../some_repo`, but we can't find a single candidate to match both requirements, hence the conflict.

The recommendation is to avoid such conflict in requirements, one possible workaround is to lock for **dev only** with `pdm lock --dev --default --lockfile pdm.dev.lock`, but then you have to specify `--lockfile pdm.dev.lock` when installing dev group.

**Comment by marcel-goldschen-ohm** [comment]
Sounds good, thanks for the explanation. It would be cool if the special handling could also handle the repo case, but if that is not easily implemented I can make due. At least I now know what the issue is, which was nonintuitive for me given the behavior with some_pypi_package. Cheers!
