### ISSUE TITLE
Version Resolution failure

### ISSUE THREAD

**Issue by Ierezell** [pdm-project/pdm#501]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce
-  `pdm init`
-  `pdm add packages`
-  `pdm add other_packages` => InconsistentCandidate error

If I do `pdm add packages other_packages` it works. 

I guess the resolution of depencies is made in the second case but fail in the first one...

## Actual behavior
Get an `InconsistentCandidate error` when adding by steps (but works if adding a bunch). 

Also (maybe not related) but sklearn got a version of `~=0.0` which seems to works but seems weird. 

## Expected behavior
Install packages normally like with pip.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.6.2                                     
Python Interpreter: /usr/bin/python (3.9)                     
Project Root:       /mnt/Projets/python-nlu                   
Project Packages:   /mnt/Projets/python-nlu/__pypackages__/3.9
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.5",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.12.9-arch1-1",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT Thu, 03 Jun 2021 11:36:13 +0000",
  "python_full_version": "3.9.5",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

Thanks in advance, 

Have a great day

**Comment by frostming** [comment]
Can you give the concrete package names because I can't reproduce with arbitrary packages.

**Comment by lazarillo** [comment]
However, on the assumption this can happen in at least some cases, it suggests that maybe some sort of reactive / retrospective versioning would be needed.

For instance, let's say that `pdm add requests flask` creates a `pyproject.toml` containing:

    dependencies = ["requests~=2.25", "flask~=1.1.4"]

but that `pdm add flask` by itself creates:

    dependencies = ["flask~=2.0"]

(This isn't true, but just to give a concrete case, let's pretend it is.)

-----

Then when the user runs `pdm add requests` *after previously running `pdm add flask`*, then it should roll back the version of Flask to 1.1.4 (maybe after asking the user if this downgrade is acceptable), so that the final result again has:

    dependencies = ["requests~=2.25", "flask~=1.1.4"]

Can this sort of change be implemented?  Is there an area of the code where I could help?

Of course, we would need a few concrete example packages to test whether it is working, as you said, @frostming 

But do you think this would be a reasonable way to address the issue?  It could potentially create breaking changes, by altering the versions of packages that have already been used in the project.  I cannot think of a better solution, though.

**Comment by Ierezell** [comment]
Hi @lazarillo, @frostming, 

Thanks for taking time on that. 

My full package list is : 

```
"spacy-transformers", 
"torch==1.8.0",
"uvicorn",
"uvloop",
"rich",
"fastapi",
"sklearn",
"sklearn-crfsuite",
"recognizers-text-suite",
"claucy @ git+git://github.com/Ierezell/spacy-clausie.git@master",
"parrot @ git+https://github.com/PrithivirajDamodaran/Parrot_Paraphraser.git@main", 
"pytesseract",
"pdf2image",
"scrapy",
"python-multipart
```

I forced torch 1.8.0 because the 1.8.1 cannot build with distutils (#500). 
Also I agree with the @lazarillo solution, installing to make everything compatible and raise a message to the user seems the easiest solution. 

Have a great day

**Comment by lazarillo** [comment]
If I understand `pdm add --unconstrained` correctly, you can specify an exact package instead of letting the resolver figure it out.  Is that correct?

So, to address the example I gave above, you could just add `flask~=1.1.4` to convert flask back from 2.0, then add requests with a normal `pdm add requests`.  Is that right?

So in these cases where pre-installed libraries need to change version, we will just figure it out manually and force that update?  This seems a good 80/20 rule balance.  :)

**Comment by frostming** [comment]
@lazarillo Not exactly

`pdm add --unconstrained requests` will *relax* the version constraints of existing packages to make it possible to pick another version that is compatible with the newly added package.

**Comment by lazarillo** [comment]
Super cool!  So does that mean that it re-evaluates *all* of the packages that `requests` relies upon (and perhaps all of the packages that those packages depend upon), and resolves that collection of all current packages + `requests`?

For example, `requests` requires `chardet`, `idna`, `urllib`, and `certifi`.  Let's also pretend that `urllib` requires `six` (I thought it did).  Finally, let's say that I already have `urllib`, `certifi`, and `six` on my machine.  Then `pdm add --unconstrained requests` would do the following:

1. Discover that those 5 packages are needed to support `requests` (the 4 direct requirements, and the indirect requirement of `six`).
1. Collect the versions of those 5 packages which would support the most recent version of `requests` supported by the version of Python being used.
1. Re-install any of those 3 packages that are already on my machine (`urllib`, `certifi`, `six`) that require a re-install to provide the most recent version of `requests` as determined in step 2.
1. Install the remaining 3 packages which didn't exist on my machine yet (`chardet`, `idna`, and `requests` itself), again using the versions determined in step 2.

Assuming this is all correct, I have 1 final question (thanks for your patience):

- What if there is a range for what the most recent version of `requests` needs, and I have a valid version, but not the most recent?
    -  For example, what if the version of `requests` being installed via `pdm add --unconstrained` allows for `urllib` version >= 1.25, and I have version 1.25.5 already installed, but version 1.26.5 is the most recent available which fulfills `requests`' needs?  Will the `--unconstrained` flag still update to 1.26.5 because while I have _an_ acceptable version of `urllib`, I do not have _the most recent_ acceptable version?

**Comment by frostming** [comment]
For your final question, `--unconstrained` controls whether the specifiers in **pyproject.toml** should change, not what versions should be **pinned** which  is locked in `pdm.lock`. And if my previous comment gives you the wrong impression, correct me now.

Say you have following content in pyproject.toml:

```toml
[project]
dependencies = [
    "urllib3<1.26"
]
```
And `urllib3==1.25.1` is pinned in `pdm.lock`. Now the latest version of urllib3 is `1.25.6` and when you do `pdm add --unconstrained requestrs`:

1. Due to the effect to `--unconstrained`, `<1.26` is stripped from the requirement, now the requirements are like `["urllib3", "requests"]`.
2. The requirements are then fed into the resolver to get a resolution. The resolver finds that the latest version of requests requires `urllib3 >=1.25.0`.
3. Due to the effect of the default update strategy(**reuse**), the pinned version of `urllib3==1.25.1` gets **reused**.
4. So the pinned version of `urllib3` in `pdm.lock` is unchanged.
5. Due to the effect of the default version-save strategy(**compatible**), PDM updates the requirement string of `urllib3` `pyproject.toml` as `urllib3~=1.25`.
6. Now the pyproject.toml looks like:
    ```toml
    [project]
    dependencies = [
        "urllib3~=1.25",
        "requests~=2.25",
    ]
    ```
   And the urllib3 version installed is kept untouched.
Note that the default strategies in step 3 and 5 can be overridden by CLI options, see how to do it by `pdm add --help`.

**Comment by lazarillo** [comment]
Awesome, thanks so much @frostming !  It's really great to see an actual example explained.  The interaction between the resolver and the update strategy were not clear to me.  Hugely helpful!  :)
