### ISSUE TITLE
Subcommand like `pdm new`

### ISSUE THREAD

**Issue by Eliot00** [pdm-project/pdm#503]
## Describe the solution you'd like

Add a sub-command like `pdm new` to creat a new Python project with a default template (`src/`, `.gitignore`, etc).

**Comment by frostming** [comment]
pdm init -p <path_to_create> will do the trick

**Comment by frostming** [comment]
Oh, you mean project template? This needs discussion though

**Comment by lazarillo** [comment]
Yeah, I feel like project templating can already be handled better by projects like cookiecutter or pyscaffold, right?

**Comment by pawamoy** [comment]
Indeed, I'd rather see PDM promote its [copier-pdm](https://github.com/prdm-project/copier-pdm) template rather than add a less powerful scaffolding command to the PDM CLI. Users can even search for such templates using "copier" and "pdm" as topics. Here's mine for example: https://github.com/pawamoy/copier-pdm/pawamoy.

But of course the decision is @frostming's :slightly_smiling_face: 
If he wants to add such a `pdm new` command, it's totally fine by me. Maybe this would help PDM newcomers, or even Python newcomers.

**Comment by frostming** [comment]
Agree with @pawamoy, I prefer to use dedicated tools to do specific jobs rather than integrating all stuff into PDM. For this reason, PDM doesn't have a `publish` command because `twine` does it well, it doesn't have a `version` command because `bump2version` does it well.

For project templating, cookiecutter and copier already do a great job and I am using the latter as well. There are various project templates to fit different needs and project types over there in the marketplace. I don't want to restrict users with one selected template provided by PDM.

**Comment by Eliot00** [comment]
想了想确实，没必要集成太多功能让PDM变的臃肿，抱歉回复晚了 @frostming

**Comment by earonesty** [comment]
i think the reason people like templates is to get a quick example of a valid project, not some generic system.

**Comment by lazarillo** [comment]
The reason I explicitly mentioned `cookiecutter` and `pyscaffold` is so that someone new to the Python world who stumbled across this post would have some idea of what tools she could use to get the job done.

But I think it is fair to say that "someone" can create a cookiecutter template that is also using pdm.  There are hundred's of templates, no harm in adding another.  Then maybe that template can be added to the docs of pdm to act as a "live" tutorial.

@frostming , let me know if you think that is worth the effort and I can create a cookiecutter template and update these docs to reference it.

Also, what do you all think, @frostming , @pawamoy , and whoever else knows the tools:  is pyscaffold better, cookiecutter, or something else that I don't know about?  I know cookiecutter best, but I've been looking for an excuse to play around with pyscaffold.

**Comment by pawamoy** [comment]
@lazarillo I used Cookiecutter a lot in the past, and eventually switched to Copier which I found absolutely better than Cookiecutter, partly thanks to its built-in update feature. I'll let you check its docs and README 🙂 
I just read again PyScaffold's README, and it seems to be way too "old-school" for me. It seems to offer only *one* template, while CookieCutter and Copier can be derived into an infinite number of templates, allowing you to define the perfect template *for you*. Sphinx, setupools, tox, pre-commit... I don't use any of these tools, so PyScaffold is not for me 😕

**Comment by frostming** [comment]
I created a curated "awesome list" containing some great projects and tools about pdm: https://github.com/pdm-project/awesome-pdm, it also contains two copier templates from me and @pawamoy

**Comment by frostming** [comment]
I think we have come to a conclusion not to add `new` command. I am going to close it for now. It might be reopened if any new idea related to this is proposed.
