### ISSUE TITLE
pdm overwrites hidden password in index url with real password

### ISSUE THREAD

**Issue by mr-rodgers** [pdm-project/pdm#561]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

1. In my pyproject, I have an index source where the password is hidden by an env variable:
```toml
url = "https://user:${GITLAB_INDEX_PASSWORD}@pypi.host/path/to/packages/pypi/simple"
```
2. I run `pdm install <pkg-from-registry>`

## Actual behavior

PDM edits `pyproject.toml` and inserts the password, so afterwards it looks like:

```toml
url = "https://user:<registry-password-in-plain-text>@pypi.host/path/to/packages/pypi/simple"
```

## Expected behavior

Original url with shadowed variable should remain in tact

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
08:48 $ pdm info && pdm info --env
PDM version:        1.7.0                                                   
Python Interpreter: /home/mr-rodgers/.pyenv/shims/python (3.9)                   
Project Root:       /home/mr-rodgers/<snipped>                   
Project Packages:   /home/mr-rodgers/<snipped>
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.6",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.4.72-microsoft-standard-WSL2",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Wed Oct 28 23:40:43 UTC 2020",
  "python_full_version": "3.9.6",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

**Comment by ElijahSink** [comment]
@frostming I'm not sure if the fix for this caused an issue that I'm seeing, or if this issue should be created separately.
The index URL is not having environment variables expanded when pip tries to install `pdm-pep517`.
```
$ pdm install -v
Preparing isolated env for PEP 517 build...
Looking in indexes: https://%24%7BPYPI_USER%7D:****@private.package.index/simple
ERROR: Could not find a version that satisfies the requirement pdm-pep517 (from versions: none)
ERROR: No matching distribution found for pdm-pep517
Failed to build package, try parsing project files.
...
```

This is the configuration in my `pyproject.toml`:
```toml
[[tool.pdm.source]]
url = "https://${PYPI_USER}:${PYPI_PASS}@private.package.index/simple"
verify_ssl = true
name = "pypi"
```

The variables are expanded properly when PDM is actually resolving my dependencies.

Changing the `name` field above to something else like "internal" fixes this issue, because the definition of the `pypi` index remains unchanged. However, this means that private packages might get sourced from the public index if there are name collisions and the version numbers are right.
