### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by caldevcani** [pdm-project/pdm#855]
I have a brand new Linux Mint system and I have Python 3.8 as the default. I installed PDM as per the instructions. After initializing the directory with 'pdm init' I tried to install fastapi by running pdm install fastapi and it tells me it's installing fastapi and a bunch of other packages. When I try and run it it tells me it cannot find fastapi. How can it not find the package if I just installed it? After running pip install fastapi I am able to run the code. Am I doing something wrong or what as this makes no sense whatsoever?

**Comment by GoodGuyGroves** [comment]
Hi @caldevcani ,

I have a similar issue to you, while I don't know what is causing my problem directly (possibly different to you because of my setup), I do know how to work around the issue.

Before you can start using PDM you need to make sure your PYTHONPATH variable is set correctly. To do that you can run this command in your terminal before trying to execute your script `eval "$(pdm --pep582)"`. That should prepend your PYTHONPATH variable with the location to your PDM install. Now, according to what I have read/seen, you should be able to just run `python3 myfile.py` directly and PDM should handle the rest. If it is still not working for you then keep reading.

If the above did work for you, next you would want to make the effects of the above `eval` command permanent. To do this you should edit your .bashrc file that is likely sitting at `~/.bashrc` and then add this at the bottom and restart your terminal: 
```
# PDM append PYTHONPATH
eval "$(pdm --pep582)"
```

If the above did not work for you, the problem is that you are using the wrong `python3` binary to execute your script. Initially when you tried to run your script it was not using PDM and instead it was calling your global python binary which is why it said FastAPI was not installed - it was indeed installed by PDM but locally to your script, not globally. Then when you used `pip` to install FastAPI, it was then installed globally... So your subsequent execution of your script then worked. To confirm this you can run `which python3` and the path returned is likely not the path of the correct python version you selected during `pdm init`.

We can work around this by making use of `pdm run`. Since you are using FastAPI there are two methods you can use to run your script.

If you have something like this in your script:
```python
if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
```
Then you can run your script like this:
```bash
pdm run python3 main.py
```

If you have been running your script by calling uvicorn directly like this:
```bash
uvicorn main:app --reload
```
Then you can run your script like this:
```bash
pdm run python3 -m uvicorn main:app --reload
```

I hope that helps!

**Comment by caldevcani** [comment]
Thank you for the information I am going to try what you suggested and hopefully it works.
