### ISSUE TITLE
Add commands to manage PDM itself (update, uninstall, etc)

### ISSUE THREAD

**Issue by wikiped** [pdm-project/pdm#900]
## Is your feature request related to a problem? Please describe.

There is an extensive section in README on how to install PDM - which is great.

However, when it comes to uninstalling PDM there seems to be no way to uninstall it properly, taking into account possible configuration changes (like for example different from the default `PDM_HOME` or `cache_dir`).

If PDM was installed with `install-pdm.py` from github it is unclear how to update it to the latest version, except for running the same script again, but again the changes to configuration that might have been made will be lost (with the exception of `PDM_HOME`).

## Describe the solution you'd like

One possible solution could be to follow `poetry`'s way and add `self` sub-command with relevant `update`, `uninstall` / `remove` sub-commands.

So, that one could run:

```shell
pdm self update

pdm self uninstall
```

**Comment by pawamoy** [comment]
Depending on how you installed PDM, it will output a hint on how to update it when there's a new version.
In my opinion, adding `self` commands like Poetry has is unnecessary and just adds complexity to the code and UX.
Tools like `pipx` are perfectly able to install and uninstall other tools like PDM.
Maybe the documentation README can better state on to uninstall when the `curl` method is used though :slightly_smiling_face:

**Comment by wikiped** [comment]
Well, some might see dependence on a external tool (i.e. `pipx`) as complexity as well, since it is not a requirement for PDM. And I am quite sure not everybody is using `pipx` 🙂

The main concern with external tools (`pip` including) is that they can not take into account config changes made by the user, which can have significant impact on filesystem (like moving cache or `PDM_HOME`)

**Comment by pawamoy** [comment]
> Well, some might see dependence on a external tool (i.e. pipx) as complexity as well, since it is not a requirement for PDM. And I am quite sure not everybody is using pipx slightly_smiling_face

Yup, that's fair :slightly_smiling_face:

**Comment by frostming** [comment]
Note that even Poetry self-command only supports `update`, and it doesn't support `uninstall` for reasons:

- Every installation may be totally different from others depending on the platform, package management, or software policy.
- `caches` folder needs to be removed, too.
- If PDM is installed via `install-pdm.py`, the venv should be removed, too.
- On Windows, the uninstallation can't be working because the process holds the ownership of the files, which prevents them from being removed.

To conclude, we are unlikely to support self-uninstallation. For self-update, as @pawamoy 's first comment says, there is a hint for it. So implementing such a command isn't that useful.

**Comment by xanterx** [comment]
The hint helpful but when I am connected to my enterprise network (vpn). No hint is displayed. I have to disconnect from the network to get the hint, having an explicit command to update pdm would definitely help some users.

**Comment by frostming** [comment]
See my last comment, software can't delete itself on Windows, making this command useless. Poetry's `self update` doesn't even work for other installation methods than `install-poetry.py`. There are many limitations but your network issue isn't something that I should consider.

**Comment by cye18** [comment]
> Depending on how you installed PDM, it will output a hint on how to update it when there's a new version.

@pawamoy Could you give me a hint on where the hint is 🤣? I didn't see it when I installed it recently with `curl` command. Here is my `curl` output. Thanks a lot!
![image](https://user-images.githubusercontent.com/83248325/162058897-17b9638a-5837-4404-a10f-b15cae4de78a.png)


> Maybe the documentation/README can better state how to uninstall when the `curl` method was used though 🙂

I think it's worth as well adding a document for updating PDM when the `curl` method was used.

@frostming Btw, on a separate topic, since it's easier to manage (update/uninstall) PDM using a package manager (like `pip` or `pipx`), why is `curl` still the recommended way to install? In other words, what's the downside of using `pip` or its alternatives? Thanks for entertaining the naive question 😆

**Comment by pawamoy** [comment]
The hint appears when you run a PDM command:

```console
% pdm install
Synchronizing working set with lock file: 0 to add, 1 to update, 0 to remove

  ✖ Update pytest 6.2.5 -> 7.1.1 failed
  Retry failed jobs
  ✔ Update pytest 6.2.5 -> 7.1.1 successful
Installing the project as an editable package...
  ✔ Update griffe 0.14.1.dev3+g21e6bd5 -> 0.15.1.dev5+g551db28.d20220406 successful

🎉 All complete!

PDM 1.13.5 is installed, while 1.13.6 is available.
Please run $ pipx upgrade pdm to upgrade.
Run $ pdm config check_update false to disable the check
```

**Comment by cbini** [comment]
> The hint appears when you run a PDM command:

it seems to have stopped doing that actually. I'm currently on 1.13.6 with `check_update = True` and I can't get the hint

**Comment by frostming** [comment]
> > The hint appears when you run a PDM command:
> 
> it seems to have stopped doing that actually. I'm currently on 1.13.6 with `check_update = True` and I can't get the hint

It checks the latest version on a weekly basis. 1.14.0 is released today and the cache isn't refreshed yet.

**Comment by cbini** [comment]
ah that explains it. thanks @frostming 

@cye18 the default venv path is `~/.local/share/pdm/venv/bin`. My understanding is that the install script creates its own venv so as not to rely on the system python or accidentally installing it into an existing venv. `pipx` does effectively the same thing, but it's another dependency, so I imagine the simplest install method is going to be the recommended one.

On the other hand, I can't say if there are any potential pitfalls to installing with pipx.
