### ISSUE TITLE
Install dev dependencies through pip install package[dev]

### ISSUE THREAD

**Issue by JaviFuentes94** [pdm-project/pdm#910]
Sometimes the end-user of a package will be using `pip` directly without `pdm` for installation. In those cases, it would be nice if the user could `pip install package-name[dev]` and install also dev dependencies. 

I have tried this as `pip install "package-name[dev]"` but it ends up installing the `prod` dependencies only. Is there a way aorund this? 

Thanks!

**Comment by frostming** [comment]
For doing this you need to specify the dev dependencies under `[project.optional-dependencies]`, instead of `[tool.pdm.dev-dependencies]`.

```toml
[project.optional-dependencies]
dev = ["pytest", "flake8"]
```

The differences between the two sections are `project.optional-dependencies` is a part of the package metadata and will be written into `METADATA` inside the built wheel. Then all groups under it are installable with `package_name[extras]` syntax. But `tool.pdm.dev-dependencies` are for the use of the project only. They are read by `pdm` to set up your project properly.
