### ISSUE TITLE
Add option to `pdm remove` to only remove specified packages(s)

### ISSUE THREAD

**Issue by DUOLabs333** [pdm-project/pdm#968]
## Is your feature request related to a problem? Please describe.
I want to reinstall a package though a manually built wheel, so I want to uninstall the package and reinstall it with `pdm add ./<name of wheel>`. However `pdm remove <package>` uninstalls not only the package, but every other package that now becomes an orphan.

## Describe the solution you'd like
Maybe an option for `pdm remove --only <package>` that only uninstalls that package, not anything else?

**Comment by frostming** [comment]
Do you agree that the environment should be kept in sync with the lock file and the lock file should be kept in sync with the `pyproject.toml` dependencies? Then what do you think of this feature request?

**Comment by DUOLabs333** [comment]
Usually, yes -- that's why I asked for a switch as a special case. `pdm sync` would then sync it properly.

**Comment by DUOLabs333** [comment]
I got around this with `pdm add -e ./<package>`, which is ideal for my needs, but there are some scenarios where I want to reinstall a wheel.

**Comment by DUOLabs333** [comment]
Maybe you could just remove the `pypackages` of that module?

**Comment by frostming** [comment]
Every requested feature might be useful and can solve some problems of some people. The difficult part is to design the interface, trying to make the option not too specific and can interact with other commands in CLI. This is a process that needs extreme carefulness and some inspiration. Otherwise the CLI will become a stacking of independent functionalities and be hard to learn and memorize.

I am not rejecting the idea, but to excuse me for not replying this issue.

**Comment by cacampbell** [comment]
PDM should not touch site-packages that are globally installed.
